### ISSUE TITLE
[Feature Request] Make homescreen search widget functional and not just a shortcut to the DuckDuckGo app

### ISSUE THREAD

**Issue by nikolowry** [duckduckgo/android-search-and-stories#265]
As a FOSS AOSP user - one of the features I miss from the Google Launcher is a functional search bar widget that launches my default browser with a query.

It'd be awesome if this use-case could be accounted for in your widget.

**Comment by poppypundit** [comment]
Isn't there an option to open search  in default browser within settings? I think its "Use External Browser" with options always/Never.

**Comment by nikolowry** [comment]
@poppypundit the flow goes as such:
- widget looks like an input on the homescreen
- go to touch widget to input a search and instead of the keyboard popping up, the DuckDuckGo app launches at it's start screen. 
- From there if you enter a search it will launch your browser if the preference you mentioned is selected.

What I'd love:
- click on the homescreen widget and a keyboard pops up and I'm able to type a query in the widget
- on enter it launches the browser

----

Off-topic: It be amazing if DuckDuckGo maintained an open-source forked version of SWE (Chromium Browser for Snapdragon) and ensured it was always on stable and included DuckDuckGo as a search provider!  The few that stay up-to-date are closed source and don't always include DuckDuckGo
