### ISSUE TITLE
Scroll position resets to top after opening in external browser

### ISSUE THREAD

**Issue by hsanjuan** [duckduckgo/android-search-and-stories#299]
Coming back to the DuckDuckGo app after viewing an article (which opens in an external browser) resets the scrolling position to the top. Happens in the latest GooglePlay version (arrived today for me).

It's a behaviour change and it is very annoying since you have to re-scroll to the place you were to keep catching up on updates after opening one.

Doesn't seem to happen when using the embedded browser.

**Comment by SubhrajyotiSen** [comment]
This issue can be closed as the fix has been merged in #301

**Comment by fgei** [comment]
yep, closing now
