### ISSUE TITLE
F-Droid Search & Stories app is out-of-date

### ISSUE THREAD

**Issue by tagawa** [duckduckgo/android-search-and-stories#307]
It looks like F-Droid is still picking up v3.0.14 which doesn't seem to be the latest version (v3.0.17 or v3.1.0).
Link: http://fdroid.org/packages/com.duckduckgo.mobile.android/

**Comment by tagawa** [comment]
F-Droid are happy to update their page but need to know which version we want them to use.
The latest version with a tag is 3.1.0 but the latest version marked "release" is 3.0.17 - see: https://github.com/duckduckgo/android-search-and-stories/releases

If not 3.1.0 then please could we remove that tag?

F-Droid discussion for reference: https://gitlab.com/fdroid/fdroiddata/issues/807

/cc @subsymbolic

**Comment by tagawa** [comment]
Thanks for the release update @subsymbolic, I've let F-Droid know.

**Comment by breversa** [comment]
Latest available version on F-Droid is 3.0.14 : https://f-droid.org/wiki/page/com.duckduckgo.mobile.android#3.1.1

**Comment by licaon-kter** [comment]
3.1.1 is out

**Comment by tagawa** [comment]
Yes, they fixed it! Seems like it was a hard-to-track-down bug in their build system but should be OK now. Thanks for letting us know @licaon-kter.
